first_boot: true
prompt: '~$ '
message: 'Welcome to rsh, v1.39. Enter “help” for help.'
# Hey there! If you want to know how to change your ASCII art logo on startup, just simply replace the logo in logo.txt with your ASCII art! Make sure you ran enable_logo too, Got it?
ascii: 'logo.txt'
